In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import pairwise_distances

In [9]:
import pandas as pd

movies = pd.read_csv("/content/drive/My Drive/Data/Movie dataset/Small/movies.csv",encoding="Latin1")
Ratings = pd.read_csv("/content/drive/My Drive/Data/Movie dataset/Small/ratings.csv")
Tags = pd.read_csv("/content/drive/My Drive/Data/Movie dataset/Small/tags.csv",encoding="Latin1")

print(movies.shape)
print(Ratings.shape)
print(Tags.shape)

(2500, 3)
(264505, 4)
(94875, 4)


In [10]:
movies.head()

movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [11]:
Ratings.head()

userId  movieId  rating   timestamp
0   12882        1     4.0  1147195252
1   12882       32     3.5  1147195307
2   12882       47     5.0  1147195343
3   12882       50     5.0  1147185499
4   12882      110     4.5  1147195239

In [13]:
Mean = Ratings.groupby(by="userId",as_index=False)['rating'].mean()
Mean

userId    rating
0       316  3.329457
1       320  3.701613
2       359  3.685474
3       370  3.794404
4       910  3.898080
..      ...       ...
857  137609  3.711538
858  137805  2.779210
859  138072  2.432927
860  138176  4.107143
861  138200  3.422249

[862 rows x 2 columns]

In [14]:
Rating_avg = pd.merge(Ratings,Mean,on='userId')
Rating_avg # rating_x: rating in each movie; rating_y: average rating all movie

userId  movieId  rating_x   timestamp  rating_y
0        12882        1       4.0  1147195252  4.061321
1        12882       32       3.5  1147195307  4.061321
2        12882       47       5.0  1147195343  4.061321
3        12882       50       5.0  1147185499  4.061321
4        12882      110       4.5  1147195239  4.061321
...        ...      ...       ...         ...       ...
264500   90097    54286       5.0  1336143258  3.963415
264501   90097    60069       4.5  1336144698  3.963415
264502   90097    68358       5.0  1336144031  3.963415
264503   90097    68954       5.0  1336146596  3.963415
264504   90097    73017       4.0  1336148879  3.963415

[264505 rows x 5 columns]

In [15]:
Rating_avg['adg_rating']=Rating_avg['rating_x']-Rating_avg['rating_y']
Rating_avg.head() # phim nao co rating cao hon muc trung binh cua 1 user

userId  movieId  rating_x   timestamp  rating_y  adg_rating
0   12882        1       4.0  1147195252  4.061321   -0.061321
1   12882       32       3.5  1147195307  4.061321   -0.561321
2   12882       47       5.0  1147195343  4.061321    0.938679
3   12882       50       5.0  1147185499  4.061321    0.938679
4   12882      110       4.5  1147195239  4.061321    0.438679

In [16]:
Tags.head()

movieId  userId           tag   timestamp
0     3916   12882        sports  1147195545
1     4085   12882  Eddie Murphy  1147195966
2    33660   12882        boxing  1147195514
3     1197     320     must show  1145964801
4     1396     320     must show  1145964810

In [17]:
check = pd.pivot_table(Rating_avg,values='rating_x',index='userId',columns='movieId')
check.head()

movieId  1       2       3       4       ...  111362  111759  112556  112852
userId                                   ...                                
316         2.5     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
320         NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
359         5.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
370         4.5     4.0     NaN     NaN  ...     3.0     4.5     3.5     3.0
910         5.0     4.0     3.5     NaN  ...     NaN     4.5     NaN     NaN

[5 rows x 2500 columns]

In [18]:
final = pd.pivot_table(Rating_avg,values='adg_rating',index='userId',columns='movieId')
final.head()

movieId    1         2        3       ...    111759    112556    112852
userId                                ...                              
316     -0.829457       NaN      NaN  ...       NaN       NaN       NaN
320           NaN       NaN      NaN  ...       NaN       NaN       NaN
359      1.314526       NaN      NaN  ...       NaN       NaN       NaN
370      0.705596  0.205596      NaN  ...  0.705596 -0.294404 -0.794404
910      1.101920  0.101920 -0.39808  ...  0.601920       NaN       NaN

[5 rows x 2500 columns]

In [24]:
final.shape

(862, 2500)

In [21]:
# Replacing NaN by Movie Average (fill na by column)
final_movie = final.fillna(final.mean(axis=0))

# Replacing NaN by user Average (fill na by row)
final_user = final.apply(lambda row: row.fillna(row.mean()), axis=1)

In [22]:
final_movie.head()

movieId    1         2         3       ...    111759    112556    112852
userId                                 ...                              
316     -0.829457 -0.436518 -0.468109  ...  0.234458  0.362468  0.349157
320      0.200220 -0.436518 -0.468109  ...  0.234458  0.362468  0.349157
359      1.314526 -0.436518 -0.468109  ...  0.234458  0.362468  0.349157
370      0.705596  0.205596 -0.468109  ...  0.705596 -0.294404 -0.794404
910      1.101920  0.101920 -0.398080  ...  0.601920  0.362468  0.349157

[5 rows x 2500 columns]

In [25]:
final_user.head()

movieId        1             2       ...        112556        112852
userId                               ...                            
316     -8.294574e-01  1.893404e-16  ...  1.893404e-16  1.893404e-16
320      4.297638e-17  4.297638e-17  ...  4.297638e-17  4.297638e-17
359      1.314526e+00 -1.135546e-16  ... -1.135546e-16 -1.135546e-16
370      7.055961e-01  2.055961e-01  ... -2.944039e-01 -7.944039e-01
910      1.101920e+00  1.019202e-01  ...  6.795811e-16  6.795811e-16

[5 rows x 2500 columns]

In [28]:
# user similarity on replacing NAN by user avg
b = cosine_similarity(final_user)
print(b.shape)
b

(862, 862)


array([[ 1.00000000e+00,  6.00630917e-02,  7.20754753e-02, ...,
         7.73765811e-02,  2.69240918e-02, -2.27270553e-02],
       [ 6.00630917e-02,  1.00000000e+00,  6.30541209e-02, ...,
         9.88451426e-02,  3.87524588e-02,  5.66393007e-02],
       [ 7.20754753e-02,  6.30541209e-02,  1.00000000e+00, ...,
         1.02698453e-01,  9.93065563e-02,  3.14714649e-03],
       ...,
       [ 7.73765811e-02,  9.88451426e-02,  1.02698453e-01, ...,
         1.00000000e+00,  9.49195502e-02,  6.47542404e-02],
       [ 2.69240918e-02,  3.87524588e-02,  9.93065563e-02, ...,
         9.49195502e-02,  1.00000000e+00,  8.99631810e-04],
       [-2.27270553e-02,  5.66393007e-02,  3.14714649e-03, ...,
         6.47542404e-02,  8.99631810e-04,  1.00000000e+00]])

In [29]:
np.fill_diagonal(b, 0 )

In [30]:
similarity_with_user = pd.DataFrame(b,index=final_user.index)
similarity_with_user.columns=final_user.index
similarity_with_user.head()

userId    316       320       359     ...    138072    138176    138200
userId                                ...                              
316     0.000000  0.060063  0.072075  ...  0.077377  0.026924 -0.022727
320     0.060063  0.000000  0.063054  ...  0.098845  0.038752  0.056639
359     0.072075  0.063054  0.000000  ...  0.102698  0.099307  0.003147
370     0.043266  0.027315  0.135836  ...  0.052187  0.050997  0.009950
910     0.039305  0.006811  0.076131  ...  0.073272 -0.012058  0.007610

[5 rows x 862 columns]

In [31]:
# user similarity on replacing NAN by item(movie) avg
cosine = cosine_similarity(final_movie)
np.fill_diagonal(cosine, 0 )
similarity_with_movie = pd.DataFrame(cosine,index=final_movie.index)
similarity_with_movie.columns=final_user.index
similarity_with_movie.head()

userId    316       320       359     ...    138072    138176    138200
userId                                ...                              
316     0.000000  0.921169  0.665659  ...  0.671783  0.949138  0.740220
320     0.921169  0.000000  0.687225  ...  0.695382  0.973853  0.768459
359     0.665659  0.687225  0.000000  ...  0.489595  0.707370  0.534065
370     0.673486  0.691158  0.534369  ...  0.497332  0.714011  0.546637
910     0.694247  0.699527  0.523475  ...  0.509008  0.725896  0.554105

[5 rows x 862 columns]

In [32]:
def find_n_neighbours(df,n):
    order = np.argsort(df.values, axis=1)[:, :n] # ??? no need this function
    df = df.apply(lambda x: pd.Series(x.sort_values(ascending=False)
           .iloc[:n].index, 
          index=['top{}'.format(i) for i in range(1, n+1)]), axis=1)
    return df

In [59]:
# top 30 neighbours for each user
sim_user_30_u = find_n_neighbours(similarity_with_user,30)
sim_user_30_u.head()
# Tim xem 30 user nao gan voi cac user ID cho truoc theo diem so user rating trung binh
# toan bo phim cua tung user

top1    top2    top3   top4  ...   top27   top28   top29   top30
userId                                 ...                                
316     113673  117918    9050  12882  ...   58265   89527   49830   63902
320      12288  113673   28159  79846  ...   80946   10055   64365  106512
359     102118   96482  102532  50898  ...   86768  129498  131620   58346
370      46645   42245   40768  23428  ...  117144   96482    2988  108195
910      87042  131620   67352  40768  ...   18115  114601   23428   17039

[5 rows x 30 columns]

In [87]:
# top 30 neighbours for each user
sim_user_30_m = find_n_neighbours(similarity_with_movie,30)
sim_user_30_m.head()
# Tim xem 30 user nao gan voi cac user ID cho truoc theo diem so movie rating trung binh
#cua toan bo user

top1    top2    top3   top4  ...   top27   top28   top29   top30
userId                                 ...                                
316     138176  100240   96936  51460  ...  124981   93203   81435   94333
320     138176   96936  121403   1447  ...   93203   80585  136037   22338
359     138176    1447    5268  96936  ...   57474   27142   80585   22338
370      86309   44194  138176  24802  ...   80585   13927   21401  136037
910      96936  107991  138176  27142  ...   61755  124981   88455   78908

[5 rows x 30 columns]

Pick user 370 and user 86309 to see how similar they are

###Explain

In [51]:
df=similarity_with_user.copy()
print(df.shape)
df.head()

(862, 862)


userId    316       320       359     ...    138072    138176    138200
userId                                ...                              
316     0.000000  0.060063  0.072075  ...  0.077377  0.026924 -0.022727
320     0.060063  0.000000  0.063054  ...  0.098845  0.038752  0.056639
359     0.072075  0.063054  0.000000  ...  0.102698  0.099307  0.003147
370     0.043266  0.027315  0.135836  ...  0.052187  0.050997  0.009950
910     0.039305  0.006811  0.076131  ...  0.073272 -0.012058  0.007610

[5 rows x 862 columns]

In [52]:
n=30
order = np.argsort(df.values, axis=1)#[:, :n]
print(order.shape)
order
# Returns the indices that would sort an array (index column id only)

(862, 862)


array([[682, 506, 332, ...,  44, 729, 704],
       [694, 720, 332, ..., 178, 704,  64],
       [332, 659, 730, ..., 637, 595, 634],
       ...,
       [691, 793, 332, ..., 207,  52, 417],
       [323, 290, 601, ..., 317, 254, 341],
       [318, 528, 447, ..., 557,  84,  64]])

In [57]:
np.sort(order[0])[:30]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
df = df.apply(lambda x: pd.Series(x.sort_values(ascending=False).iloc[:n].index, 
                                  index=['top{}'.format(i) for i in range(1, n+1)]),
              axis=1)
# sort value tung row theo thu tu cao xuong thap, return index of each value
print(df.shape)
df.head()
# return column name with highest value (decending)

(862, 30)


top1    top2    top3   top4  ...   top27   top28   top29   top30
userId                                 ...                                
316     113673  117918    9050  12882  ...   58265   89527   49830   63902
320      12288  113673   28159  79846  ...   80946   10055   64365  106512
359     102118   96482  102532  50898  ...   86768  129498  131620   58346
370      46645   42245   40768  23428  ...  117144   96482    2988  108195
910      87042  131620   67352  40768  ...   18115  114601   23428   17039

[5 rows x 30 columns]

###End

Lets check our self whether what we calculated really makes sense !!

In [108]:
def get_user_similar_movies( user1, user2 ):
    common_movies = Rating_avg[Rating_avg.userId == user1].merge(
    Rating_avg[Rating_avg.userId == user2],
    on = "movieId",
    how = "inner" )
    common_movies.movieId=common_movies.movieId.astype('int64')
    return common_movies.merge( movies, on = 'movieId' )

In [109]:
a = get_user_similar_movies(370,86309)
a = a.loc[ : , ['rating_x_x','rating_x_y','title']]
a.head()
# tim xem 2 user nay co nhung phim nao chung, xem rating va movie cac phim nay

rating_x_x  rating_x_y                                              title
0         5.0         5.0                                 Matrix, The (1999)
1         5.0         4.5  Lord of the Rings: The Fellowship of the Ring,...
2         5.0         4.0      Lord of the Rings: The Two Towers, The (2002)
3         4.5         4.0  Lord of the Rings: The Return of the King, The...
4         1.5         1.0                                    Serenity (2005)

###Explain

In [91]:
Rating_avg.head()

userId movieId  rating_x   timestamp  rating_y  adg_rating
0   12882       1       4.0  1147195252  4.061321   -0.061321
1   12882      32       3.5  1147195307  4.061321   -0.561321
2   12882      47       5.0  1147195343  4.061321    0.938679
3   12882      50       5.0  1147185499  4.061321    0.938679
4   12882     110       4.5  1147195239  4.061321    0.438679

In [92]:
user1=370
user2=86309

In [93]:
Rating_avg[Rating_avg.userId == user1].head()

userId movieId  rating_x   timestamp  rating_y  adg_rating
215570     370       1       4.5  1200776471  3.794404    0.705596
215571     370       2       4.0  1228059945  3.794404    0.205596
215572     370       6       5.0  1174732452  3.794404    1.205596
215573     370      25       4.5  1186944967  3.794404    0.705596
215574     370      32       5.0  1174732353  3.794404    1.205596

In [94]:
Rating_avg[Rating_avg.userId == user2].head()

userId movieId  rating_x   timestamp  rating_y  adg_rating
131642   86309    2393       3.0  1215578439  3.611111   -0.611111
131643   86309    2571       5.0  1215580355  3.611111    1.388889
131644   86309    4993       4.5  1215580294  3.611111    0.888889
131645   86309    5952       4.0  1215580301  3.611111    0.388889
131646   86309    7153       4.0  1215580304  3.611111    0.388889

In [95]:
common_movies = Rating_avg[Rating_avg.userId == user1].merge(
                          Rating_avg[Rating_avg.userId == user2],
                          on = "movieId",
                          how = "inner" )
common_movies # tim xem giua 2 user co nhung movie nao chung

userId_x movieId  rating_x_x  ...  timestamp_y  rating_y_y  adg_rating_y
0        370    2571         5.0  ...   1215580355    3.611111      1.388889
1        370    4993         5.0  ...   1215580294    3.611111      0.888889
2        370    5952         5.0  ...   1215580301    3.611111      0.388889
3        370    7153         4.5  ...   1215580304    3.611111      0.388889
4        370   34405         1.5  ...   1215578686    3.611111     -2.611111
5        370   44022         3.5  ...   1215579255    3.611111     -0.111111
6        370   46976         5.0  ...   1215578976    3.611111     -0.111111
7        370   48774         3.0  ...   1215578787    3.611111     -0.111111
8        370   51540         4.0  ...   1215579101    3.611111      0.388889
9        370   53125         1.0  ...   1215579033    3.611111      0.388889
10       370   58559         4.0  ...   1221724081    3.611111      0.388889
11       370   60069         3.5  ...   1215580229    3.611111      0.888889

[12 rows x 11 columns]

In [104]:

common_movies.movieId=common_movies.movieId.astype('int64')
common_movies.movieId

0      2571
1      4993
2      5952
3      7153
4     34405
5     44022
6     46976
7     48774
8     51540
9     53125
10    58559
11    60069
Name: movieId, dtype: int64

In [96]:
movies.head()

movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [103]:
movies.movieId

0            1
1            2
2            3
3            4
4            5
         ...  
2495    109487
2496    111362
2497    111759
2498    112556
2499    112852
Name: movieId, Length: 2500, dtype: int64

In [106]:
common_movies.merge(movies, on = 'movieId' ).head()

userId_x  ...                          genres
0       370  ...          Action|Sci-Fi|Thriller
1       370  ...               Adventure|Fantasy
2       370  ...               Adventure|Fantasy
3       370  ...  Action|Adventure|Drama|Fantasy
4       370  ...         Action|Adventure|Sci-Fi

[5 rows x 13 columns]

In [107]:
common_movies.merge(movies, on = 'movieId' ).\
loc[ : , ['rating_x_x','rating_x_y','title']].head()

rating_x_x  rating_x_y                                              title
0         5.0         5.0                                 Matrix, The (1999)
1         5.0         4.5  Lord of the Rings: The Fellowship of the Ring,...
2         5.0         4.0      Lord of the Rings: The Two Towers, The (2002)
3         4.5         4.0  Lord of the Rings: The Return of the King, The...
4         1.5         1.0                                    Serenity (2005)

###End

In [110]:
def User_item_score(user,item):
    a = sim_user_30_m[sim_user_30_m.index==user].values
    b = a.squeeze().tolist()
    c = final_movie.loc[:,item]
    d = c[c.index.isin(b)]
    f = d[d.notnull()]
    avg_user = Mean.loc[Mean['userId'] == user,'rating'].values[0]
    index = f.index.values.squeeze().tolist()
    corr = similarity_with_movie.loc[user,index]
    fin = pd.concat([f, corr], axis=1)
    fin.columns = ['adg_score','correlation']
    fin['score']=fin.apply(lambda x:x['adg_score'] * x['correlation'],axis=1)
    nume = fin['score'].sum()
    deno = fin['correlation'].sum()
    final_score = avg_user + (nume/deno)
    return final_score

In [111]:
score = User_item_score(320,7371)
print("score (u,i) is",score)

score (u,i) is 4.255766437391595


### Explain

In [116]:
sim_user_30_m

top1    top2    top3    top4  ...   top27   top28   top29   top30
userId                                  ...                                
316     138176  100240   96936   51460  ...  124981   93203   81435   94333
320     138176   96936  121403    1447  ...   93203   80585  136037   22338
359     138176    1447    5268   96936  ...   57474   27142   80585   22338
370      86309   44194  138176   24802  ...   80585   13927   21401  136037
910      96936  107991  138176   27142  ...   61755  124981   88455   78908
...        ...     ...     ...     ...  ...     ...     ...     ...     ...
137609  138176   96936    1447   51460  ...   27142   54643  121290   94333
137805   51255  138176   88932  114335  ...   54643   53819  118304  124981
138072  138176    5268   65648   51255  ...  102549  103582   54114   83479
138176   96936    1447   51460  121403  ...  102549   94333  124454   54643
138200  138176   27142   42944   96936  ...   88455  128079   93347  124454

[862 rows x 30 columns]

In [117]:
user=320
item=7371
a = sim_user_30_m[sim_user_30_m.index==user].values
a # tim xem cac user nao similar voi user vua chon

array([[138176,  96936, 121403,   1447,  51460, 125012,  88932,  42944,
          5268, 104529,  12930,  13927, 129869,  27142,  51255, 100240,
        128079,  21401, 114335, 104732, 121987, 102549, 118304,  86309,
         94333, 124981,  93203,  80585, 136037,  22338]])

In [119]:
b = a.squeeze().tolist()
print(b)

[138176, 96936, 121403, 1447, 51460, 125012, 88932, 42944, 5268, 104529, 12930, 13927, 129869, 27142, 51255, 100240, 128079, 21401, 114335, 104732, 121987, 102549, 118304, 86309, 94333, 124981, 93203, 80585, 136037, 22338]


In [121]:
final_movie

movieId    1         2         3       ...    111759    112556    112852
userId                                 ...                              
316     -0.829457 -0.436518 -0.468109  ...  0.234458  0.362468  0.349157
320      0.200220 -0.436518 -0.468109  ...  0.234458  0.362468  0.349157
359      1.314526 -0.436518 -0.468109  ...  0.234458  0.362468  0.349157
370      0.705596  0.205596 -0.468109  ...  0.705596 -0.294404 -0.794404
910      1.101920  0.101920 -0.398080  ...  0.601920  0.362468  0.349157
...           ...       ...       ...  ...       ...       ...       ...
137609   0.200220 -0.436518 -0.468109  ...  0.234458  0.362468  0.349157
137805   1.220790 -0.779210 -0.468109  ...  0.234458  0.362468  1.220790
138072   0.567073 -1.432927 -1.432927  ...  0.234458  0.362468  0.349157
138176   0.200220 -0.436518 -0.468109  ...  0.234458  0.362468  0.349157
138200  -0.422249 -0.436518 -0.468109  ...  0.234458  0.362468  0.349157

[862 rows x 2500 columns]

In [120]:
c = final_movie.loc[:,item]
c # tim xem tai colum movie id (item) co nhung user nao rating (average)

userId
316       0.554154
320       0.554154
359       0.554154
370       0.705596
910       0.554154
            ...   
137609    0.554154
137805    0.554154
138072    0.554154
138176    0.554154
138200    0.577751
Name: 7371, Length: 862, dtype: float64

In [122]:
d = c[c.index.isin(b)]
d # Loc cac user similar voi user o tren

userId
1447      0.554154
5268      0.554154
12930     0.554154
13927     0.554154
21401     0.554154
22338     0.554154
27142     0.554154
42944     0.554154
51255     0.554154
51460     0.554154
80585     0.554154
86309     0.554154
88932     0.554154
93203     0.554154
94333     0.554154
96936     0.554154
100240    0.554154
102549    0.554154
104529    0.554154
104732    0.554154
114335    0.554154
118304    0.554154
121403    0.554154
121987    0.554154
124981    0.554154
125012    0.554154
128079    0.554154
129869    0.554154
136037    0.554154
138176    0.554154
Name: 7371, dtype: float64

In [123]:
f = d[d.notnull()]
f

userId
1447      0.554154
5268      0.554154
12930     0.554154
13927     0.554154
21401     0.554154
22338     0.554154
27142     0.554154
42944     0.554154
51255     0.554154
51460     0.554154
80585     0.554154
86309     0.554154
88932     0.554154
93203     0.554154
94333     0.554154
96936     0.554154
100240    0.554154
102549    0.554154
104529    0.554154
104732    0.554154
114335    0.554154
118304    0.554154
121403    0.554154
121987    0.554154
124981    0.554154
125012    0.554154
128079    0.554154
129869    0.554154
136037    0.554154
138176    0.554154
Name: 7371, dtype: float64

In [125]:
Mean

userId    rating
0       316  3.329457
1       320  3.701613
2       359  3.685474
3       370  3.794404
4       910  3.898080
..      ...       ...
857  137609  3.711538
858  137805  2.779210
859  138072  2.432927
860  138176  4.107143
861  138200  3.422249

[862 rows x 2 columns]

In [126]:
Mean.loc[Mean['userId'] == user,'rating']

1    3.701613
Name: rating, dtype: float64

In [124]:
avg_user = Mean.loc[Mean['userId'] == user,'rating'].values[0]
avg_user # average rating of this user

3.7016129032258065

In [128]:
index = f.index.values.squeeze().tolist()
print(index)

[1447, 5268, 12930, 13927, 21401, 22338, 27142, 42944, 51255, 51460, 80585, 86309, 88932, 93203, 94333, 96936, 100240, 102549, 104529, 104732, 114335, 118304, 121403, 121987, 124981, 125012, 128079, 129869, 136037, 138176]


In [129]:
corr = similarity_with_movie.loc[user,index]
corr

userId
1447      0.970234
5268      0.968571
12930     0.968229
13927     0.967932
21401     0.966505
22338     0.963998
27142     0.967627
42944     0.968901
51255     0.967171
51460     0.969980
80585     0.964440
86309     0.964799
88932     0.969214
93203     0.964499
94333     0.964605
96936     0.972050
100240    0.967120
102549    0.964844
104529    0.968452
104732    0.966156
114335    0.966281
118304    0.964808
121403    0.970736
121987    0.965176
124981    0.964574
125012    0.969272
128079    0.966704
129869    0.967705
136037    0.964076
138176    0.973853
Name: 320, dtype: float64

In [130]:
fin = pd.concat([f, corr], axis=1)
fin

7371      320 
userId                    
1447    0.554154  0.970234
5268    0.554154  0.968571
12930   0.554154  0.968229
13927   0.554154  0.967932
21401   0.554154  0.966505
22338   0.554154  0.963998
27142   0.554154  0.967627
42944   0.554154  0.968901
51255   0.554154  0.967171
51460   0.554154  0.969980
80585   0.554154  0.964440
86309   0.554154  0.964799
88932   0.554154  0.969214
93203   0.554154  0.964499
94333   0.554154  0.964605
96936   0.554154  0.972050
100240  0.554154  0.967120
102549  0.554154  0.964844
104529  0.554154  0.968452
104732  0.554154  0.966156
114335  0.554154  0.966281
118304  0.554154  0.964808
121403  0.554154  0.970736
121987  0.554154  0.965176
124981  0.554154  0.964574
125012  0.554154  0.969272
128079  0.554154  0.966704
129869  0.554154  0.967705
136037  0.554154  0.964076
138176  0.554154  0.973853

In [131]:
fin.columns = ['adg_score','correlation']
fin.head()

adg_score  correlation
userId                        
1447     0.554154     0.970234
5268     0.554154     0.968571
12930    0.554154     0.968229
13927    0.554154     0.967932
21401    0.554154     0.966505

In [132]:
fin['score']=fin.apply(lambda x:x['adg_score'] * x['correlation'],axis=1)
fin.head()

adg_score  correlation     score
userId                                  
1447     0.554154     0.970234  0.537658
5268     0.554154     0.968571  0.536737
12930    0.554154     0.968229  0.536547
13927    0.554154     0.967932  0.536383
21401    0.554154     0.966505  0.535592

In [133]:
nume = fin['score'].sum()
deno = fin['correlation'].sum()
print(avg_user, nume, deno)
final_score = avg_user + (nume/deno)
final_score

3.7016129032258065 16.080710233866697 29.018510651699202


4.255766437391595

### End

In [112]:
Rating_avg = Rating_avg.astype({"movieId": str})
Movie_user = Rating_avg.groupby(by = 'userId')['movieId'].apply(lambda x:','.join(x))

In [113]:
def User_item_score1(user):
    Movie_seen_by_user = check.columns[check[check.index==user].notna().any()].tolist()
    a = sim_user_30_m[sim_user_30_m.index==user].values
    b = a.squeeze().tolist()
    d = Movie_user[Movie_user.index.isin(b)]
    l = ','.join(d.values)
    Movie_seen_by_similar_users = l.split(',')
    Movies_under_consideration = list(set(Movie_seen_by_similar_users)-set(list(map(str, Movie_seen_by_user))))
    Movies_under_consideration = list(map(int, Movies_under_consideration))
    score = []
    for item in Movies_under_consideration:
        c = final_movie.loc[:,item]
        d = c[c.index.isin(b)]
        f = d[d.notnull()]
        avg_user = Mean.loc[Mean['userId'] == user,'rating'].values[0]
        index = f.index.values.squeeze().tolist()
        corr = similarity_with_movie.loc[user,index]
        fin = pd.concat([f, corr], axis=1)
        fin.columns = ['adg_score','correlation']
        fin['score']=fin.apply(lambda x:x['adg_score'] * x['correlation'],axis=1)
        nume = fin['score'].sum()
        deno = fin['correlation'].sum()
        final_score = avg_user + (nume/deno)
        score.append(final_score)
    data = pd.DataFrame({'movieId':Movies_under_consideration,'score':score})
    top_5_recommendation = data.sort_values(by='score',ascending=False).head(5)
    Movie_Name = top_5_recommendation.merge(movies, how='inner', on='movieId')
    Movie_Names = Movie_Name.title.values.tolist()
    return Movie_Names

In [115]:
user = int(input("Enter the user id to whom you want to recommend : "))
predicted_movies = User_item_score1(user)
print(" ")
print("The Recommendations for User Id : 370")
print("   ")
for i in predicted_movies:
    print(i)

Enter the user id to whom you want to recommend : 320
 
The Recommendations for User Id : 370
   
Godfather, The (1972)
Shawshank Redemption, The (1994)
Godfather: Part II, The (1974)
Band of Brothers (2001)
Amelie (Fabuleux destin d'Amélie Poulain, Le) (2001)
